### ISSUE TITLE
How to display claim review box on web page

### ISSUE THREAD

**Issue by atish-31** [FullFact/claim-review-schema-wordpress-plugin#2]
I want to display the claim review box on my website article.
![unnamed](https://user-images.githubusercontent.com/50361590/69962105-4bf3b680-1533-11ea-93a4-6271e3a00267.png)

**Comment by atish-31** [comment]
Is there any update??

**Comment by MevanBabakar** [comment]
Hi Atish,

This plugin doesn't display anything on the web page to a reader, it only makes an addition to the code of web page, it adds claim review schema mark up, so that it can be crawled more efficiently by search engines or third party products. 

The change you should see is in the structured data available on the page, you can use: https://search.google.com/structured-data/testing-tool to see if it is working correctly, if so, you should see "claim review" as an option for a page that is correctly filled in.

I hope that helps.

Best,
Mevan
